export const getReviews = (getTranslation: (key: string) => string) => [
  {
    id: '1',
    respond: getTranslation('reviewsSection.reviewBrazhko.respond'),
    name: getTranslation('reviewsSection.reviewBrazhko.name'),
    label: 'B',
    style: { backgroundColor: '#2196F3', color: '#ffffff' },
  },
  {
    id: '2',
    respond: getTranslation('reviewsSection.reviewOlga.respond'),
    name: getTranslation('reviewsSection.reviewOlga.name'),
    label: 'O',
    style: { backgroundColor: '#9c27b0', color: '#ffffff' },
  },
  {
    id: '3',
    respond: getTranslation('reviewsSection.reviewSofiya.respond'),
    name: getTranslation('reviewsSection.reviewSofiya.name'),
    label: 'S',
    style: { backgroundColor: '#9c27b0', color: '#ffffff' },
  },
  {
    id: '4',
    respond: getTranslation('reviewsSection.reviewIryna1.respond'),
    name: getTranslation('reviewsSection.reviewIryna1.name'),
    label: 'I',
    style: { backgroundColor: '#9c27b0', color: '#ffffff' },
  },
  {
    id: '5',
    respond: getTranslation('reviewsSection.reviewAnastasiya.respond'),
    name: getTranslation('reviewsSection.reviewAnastasiya.name'),
    label: 'A',
    style: { backgroundColor: '#9c27b0', color: '#ffffff' },
  },
  {
    id: '6',
    respond: getTranslation('reviewsSection.reviewOksana.respond'),
    name: getTranslation('reviewsSection.reviewOksana.name'),
    label: 'O',
    style: { backgroundColor: '#9c27b0', color: '#ffffff' },
  },
  {
    id: '7',
    respond: getTranslation('reviewsSection.reviewRenata.respond'),
    name: getTranslation('reviewsSection.reviewRenata.name'),
    label: 'R',
    style: { backgroundColor: '#9c27b0', color: '#ffffff' },
  },
  {
    id: '8',
    respond: getTranslation('reviewsSection.reviewIryna2.respond'),
    name: getTranslation('reviewsSection.reviewIryna2.name'),
    label: 'I',
    style: { backgroundColor: '#9c27b0', color: '#ffffff' },
  },
  {
    id: '9',
    respond: getTranslation('reviewsSection.reviewJulia.respond'),
    name: getTranslation('reviewsSection.reviewJulia.name'),
    label: 'J',
    style: { backgroundColor: '#9c27b0', color: '#ffffff' },
  },
  {
    id: '10',
    respond: getTranslation('reviewsSection.reviewSasha.respond'),
    name: getTranslation('reviewsSection.reviewSasha.name'),
    label: 'S',
    style: { backgroundColor: '#2196F3', color: '#ffffff' },
  },
  {
    id: '11',
    respond: getTranslation('reviewsSection.reviewAndrii.respond'),
    name: getTranslation('reviewsSection.reviewAndrii.name'),
    label: 'A',
    style: { backgroundColor: '#2196F3', color: '#ffffff' },
  },
  {
    id: '12',
    respond: getTranslation('reviewsSection.reviewSofia.respond'),
    name: getTranslation('reviewsSection.reviewSofia.name'),
    label: 'S',
    style: { backgroundColor: '#9c27b0', color: '#ffffff' },
  },
];
